# Generated by Django 5.2 on 2025-04-16 04:31

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0002_candidate'),
    ]

    operations = [
        migrations.CreateModel(
            name='Voter',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
                ('election_id', models.CharField(max_length=100, unique=True)),
                ('face_encoding', models.TextField()),
                ('has_voted', models.BooleanField(default=False)),
            ],
        ),
    ]
